import { Lead } from "@/lib/types";
import { scoreLead } from "@/lib/scoring";

const rawLeads: Omit<Lead, "score">[] = [
  {
    id: "lead-001",
    companyName: "GulfSpan Contracting LLC",
    contactPerson: "Khalid Mansoor",
    jobTitle: "Procurement Manager",
    email: "khalid@gulfspan.example",
    phone: "+971 50 214 8890",
    emirate: "Dubai",
    industry: "Construction",
    projectType: "Commercial tower frame",
    projectSize: "Large",
    productsRequired: ["Universal beams", "Plates", "Hollow sections"],
    leadSource: "Trade exhibition",
    status: "Quotation Sent",
    notes: "Requested mill certificates and delivery split for Al Quoz site.",
    urgency: "High",
    pastInquiry: true,
    nextFollowUp: "2026-05-08",
    createdAt: "2026-04-24"
  },
  {
    id: "lead-002",
    companyName: "Emirates Industrial Sheds",
    contactPerson: "Ayesha Rahman",
    jobTitle: "Projects Director",
    email: "ayesha@eis.example",
    phone: "+971 55 438 2107",
    emirate: "Sharjah",
    industry: "Warehousing",
    projectType: "Warehouse expansion",
    projectSize: "Medium",
    productsRequired: ["H-beams", "Channels", "Angles"],
    leadSource: "Referral",
    status: "Contacted",
    notes: "Needs fast stock confirmation for SAIF Zone warehouse.",
    urgency: "Immediate",
    pastInquiry: false,
    nextFollowUp: "2026-05-06",
    createdAt: "2026-04-28"
  },
  {
    id: "lead-003",
    companyName: "ADN Fabrication Services",
    contactPerson: "Omar Al Nuaimi",
    jobTitle: "General Manager",
    email: "omar@adnfab.example",
    phone: "+971 52 771 3341",
    emirate: "Abu Dhabi",
    industry: "Steel Fabrication",
    projectType: "Oilfield skid packages",
    projectSize: "Mega",
    productsRequired: ["I-beams", "Pipes", "Plates"],
    leadSource: "Existing account",
    status: "Negotiation",
    notes: "Comparing CIF and ex-stock pricing for May release.",
    urgency: "High",
    pastInquiry: true,
    nextFollowUp: "2026-05-05",
    createdAt: "2026-04-18"
  },
  {
    id: "lead-004",
    companyName: "RAK Pre-Engineered Buildings",
    contactPerson: "Faisal Kareem",
    jobTitle: "Estimator",
    email: "faisal@rakpeb.example",
    phone: "+971 56 940 1283",
    emirate: "Ras Al Khaimah",
    industry: "Industrial Projects",
    projectType: "Factory mezzanine",
    projectSize: "Small",
    productsRequired: ["Flat bars", "Angles", "Channels"],
    leadSource: "Website form",
    status: "New Lead",
    notes: "Asked for indicative price only.",
    urgency: "Medium",
    pastInquiry: false,
    nextFollowUp: "2026-05-11",
    createdAt: "2026-05-01"
  },
  {
    id: "lead-005",
    companyName: "DesertLink EPC",
    contactPerson: "Nadia Haddad",
    jobTitle: "Supply Chain Lead",
    email: "nadia@desertlinkepc.example",
    phone: "+971 58 612 7098",
    emirate: "Dubai",
    industry: "EPC",
    projectType: "Industrial utility plant",
    projectSize: "Mega",
    productsRequired: ["Universal columns", "Universal beams", "Pipes"],
    leadSource: "LinkedIn",
    status: "Won",
    notes: "First delivery completed. Discuss June replenishment.",
    urgency: "Low",
    pastInquiry: true,
    nextFollowUp: "2026-05-15",
    createdAt: "2026-03-30"
  },
  {
    id: "lead-006",
    companyName: "Palm District Developers",
    contactPerson: "Ravi Menon",
    jobTitle: "Construction Manager",
    email: "ravi@palmdistrict.example",
    phone: "+971 54 331 7865",
    emirate: "Ajman",
    industry: "Real Estate Development",
    projectType: "Mixed-use podium",
    projectSize: "Large",
    productsRequired: ["Hollow sections", "Plates"],
    leadSource: "Public tender notice",
    status: "Lost",
    notes: "Lost on payment terms. Revisit future packages compliantly.",
    urgency: "Medium",
    pastInquiry: false,
    nextFollowUp: "2026-06-01",
    createdAt: "2026-04-04"
  }
];

export const sampleLeads: Lead[] = rawLeads.map((lead) => ({
  ...lead,
  score: scoreLead(lead)
}));
