insert into public.leads (
  company_name,
  contact_person,
  job_title,
  email,
  phone,
  emirate,
  industry,
  project_type,
  project_size,
  products_required,
  lead_source,
  status,
  notes,
  urgency,
  past_inquiry,
  next_follow_up,
  score
) values
(
  'GulfSpan Contracting LLC',
  'Khalid Mansoor',
  'Procurement Manager',
  'khalid@gulfspan.example',
  '+971 50 214 8890',
  'Dubai',
  'Construction',
  'Commercial tower frame',
  'Large',
  array['Universal beams', 'Plates', 'Hollow sections'],
  'Trade exhibition',
  'Quotation Sent',
  'Requested mill certificates and delivery split for Al Quoz site.',
  'High',
  true,
  '2026-05-08',
  81
),
(
  'Emirates Industrial Sheds',
  'Ayesha Rahman',
  'Projects Director',
  'ayesha@eis.example',
  '+971 55 438 2107',
  'Sharjah',
  'Warehousing',
  'Warehouse expansion',
  'Medium',
  array['H-beams', 'Channels', 'Angles'],
  'Referral',
  'Contacted',
  'Needs fast stock confirmation for SAIF Zone warehouse.',
  'Immediate',
  false,
  '2026-05-06',
  74
),
(
  'ADN Fabrication Services',
  'Omar Al Nuaimi',
  'General Manager',
  'omar@adnfab.example',
  '+971 52 771 3341',
  'Abu Dhabi',
  'Steel Fabrication',
  'Oilfield skid packages',
  'Mega',
  array['I-beams', 'Pipes', 'Plates'],
  'Existing account',
  'Negotiation',
  'Comparing CIF and ex-stock pricing for May release.',
  'High',
  true,
  '2026-05-05',
  91
);
